registry:
  url: http://localhost:8081
  addoperationid: add
  searchoperationid: search
  readoperationid: read
keycloak:
  url: https://divoc.xiv.in/keycloak/auth
  realm: divoc
  facilityAdmin:
    roleName: facility-admin
    roleId: 9da3a031-0c76-4077-9176-facfe70b12bc
    clientId: f806ea15-8a99-48f9-9c5d-a4602ae7b9db
    groupId: 860560da-911e-4db1-92f2-0cbbaad8f7b3
  facilityStaff:
    roleName: facility-staff
    roleId: e5573b4d-2805-475b-8e59-d2c7c9de499e
    clientId: f806ea15-8a99-48f9-9c5d-a4602ae7b9db
    groupId: 84682840-4c21-428d-b2d5-06e6298be1cc
analytics:
  datasource: tcp://localhost:9000?debug=true
facility:
  upload:
    columns: "facilityCode,facilityName,contact,operatingHourStart,operatingHourEnd,category,type,status,addressLine1,addressLine2,district,state,pincode,geoLocationLat,geoLocationLon,adminName,adminMobile"
    required: "facilityCode,facilityName,contact,addressLine1,addressLine1,district,state,pincode,adminName,adminMobile"
preenrollment:
  upload:
    columns: "phone,identity,nationality,dob,gender,name,email,addressLine1,addressLine2,district,state,pincode"
    required: "phone,identity,nationality,dob,gender,name,addressLine1,district,state,pincode"
vaccinator:
  upload:
    columns: "code,name,nationalIdentifier,mobileNumber,email,status,facilityIds"
    required: "code,name,email,nationalIdentifier,mobileNumber,status,facilityIds"
kafka:
  bootstrapServers: localhost:9092
  notifyTopic: notify
  certifiedTopic: certified
  enrollmenttopic: enrollment
flagr:
  url: https://divoc.xiv.in/config
enrollmentcreation:
  maxretrycount: 10
  lengthofsuffixedenrollmentcode: 3
