const { body, validationResult, sanitizeBody } = require("express-validator");
const { nanoid } = require("nanoid");
const apiResponse = require("../helpers/apiResponse");
const fs = require("fs");
const moveFile = require("move-file");
const date = require("date-and-time");
require("dotenv").config();
const auth = require("../middlewares/jwt");
const checkToken = require("../middlewares/middleware").checkToken;
const WarehouseModel = require("../models/WarehouseModel");
const logEvent = require("../../../utils/event_logger/eventLogger");
const init = require("../logging/init");
const logger = init.getLog();
const imageUrl = process.env.IMAGE_URL;
