version: "3.7"
services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      - "9000:9000"
    volumes:
      - "./traefik_config/traefik.yml:/traefik.yml:ro"
      - ./traefik_config/acme.json:/acme.json
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # labels: 
    #   - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    #   - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
    #   - "traefik.http.routers.redirect-https.entrypoints=web"
    #   - "traefik.http.routers.redirect-https.middlewares=redirect-to-https"    
  frontend:
    build: './frontend'
    image: 'frontend1.0'
    container_name: 'frontend'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=Path(`/`) || PathPrefix(`/dist`)"
      # - "traefik.http.routers.whoami.tls.certresolver=lets-encr"
  address:
    build: './backend/address_service'
    image: 'address_service1.0'
    container_name: 'address_service'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.address.entrypoints=web"
      - "traefik.http.routers.address.rule=PathPrefix(`/api/address_service`)"
  affliate:
    build: './backend/affliation_service'
    image: 'affliation_service1.0'
    container_name: 'affliate_service'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.affliate.entrypoints=web"
      - "traefik.http.routers.affliate.rule=PathPrefix(`/api/affliation_service`)"  
  rbac:
    build: './backend/rbac_service'
    image: 'rbac_service1.0'
    container_name: 'rbac_service'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.rbac.entrypoints=web"
      - "traefik.http.routers.rbac.rule=PathPrefix(`/api/rbac_service`)"               
  employee:
    build: './backend/employee_service'
    image: 'employee_service1.0'
    container_name: 'employee_service'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.employee.entrypoints=web"
      - "traefik.http.routers.employee.rule=PathPrefix(`/api/employee_service`)"  
networks:
  default:
    external:
      name: proxy            
