version: "3.7"
services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "./traefik_config/traefik.yml:/traefik.yml:ro"
      - ./traefik_config/acme.json:/acme.json
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  
  frontend:
    build: './frontend'
    image: 'frontend1.0'
    container_name: 'frontend'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=Host(`admin.vaccineledger.com`) && PathPrefix(`/`)"
  address:
    build: './backend/address_service'
    image: 'address_service1.0'
    container_name: 'address_service'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.address.entrypoints=web"
      - "traefik.http.routers.address.rule=Host(`admin.vaccineledger.com`) && PathPrefix(`/api/address_service`)"
  affliate:
    build: './backend/affliation_service'
    image: 'affliation_service1.0'
    container_name: 'affliate_service'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.affliate.entrypoints=web"
      - "traefik.http.routers.affliate.rule=Host(`admin.vaccineledger.com`) && PathPrefix(`/api/affliation_service`)"  
  rbac:
    build: './backend/rbac_service'
    image: 'rbac_service1.0'
    container_name: 'rbac_service'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.rbac.entrypoints=web"
      - "traefik.http.routers.rbac.rule=Host(`admin.vaccineledger.com`) && PathPrefix(`/api/rbac_service`)"               
  employee:
    build: './backend/employee_service'
    image: 'employee_service1.0'
    container_name: 'employee_service'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.employee.entrypoints=web"
      - "traefik.http.routers.employee.rule=Host(`admin.vaccineledger.com`) && PathPrefix(`/api/employee_service`)"
    environment: 
      MONGODB_URL=mongodb://StaTwig:StaTwig2020@db.vaccineledger.com:27017/development
      LOGZ_LEVEL='info'
      LOGZ_NAME='winston_logzio'
      LOGZ_TOKEN='KqhemFAnVcNnIYErrIVtTPTupVJzlvvV'
      LOGZ_HOST='listener.logz.io'
      JWT_SECRET=abcdefghijklmnopqrstuvwxyz1234567890
      JWT_TIMEOUT_DURATION="2 hours"
      EMAIL_SMTP_HOST=smtp.gmail.com
      EMAIL_SMTP_PORT=587
      EMAIL_SMTP_USERNAME=info@babyboo.in
      EMAIL_SMTP_PASSWORD=NetStar2019
      EMAIL_SMTP_SECURE=false
      URL='http://15.206.159.129:3008/blockchainmanagement'
  
networks:
  default:
    external:
      name: proxy            
