# [http.middlewares.simpleAuth.basicAuth]
#   users = [
#     "admin:$apr1$ruca84Hq$mbjdMZBAG.KWn7vfN/SNK/"
#   ]
# [http.routers.api]
#   rule = "Host(`test.traefik.vaccineledger.com`)"
#   entrypoints = ["websecure"]
#   middlewares = ["simpleAuth"]
#   service = "api@internal"
#   [http.routers.api.tls]
#     certResolver = "lets-encrypt"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS13"
    sniStrict = true
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    ]