# http routing section
[http]
  [http.routers]
     # Define a connection between requests and services
    [http.routers.to-whoami]
      rule = "Host(`127.0.0.1`) && PathPrefix(`/`)"
      # If the rule matches, applies the middleware
      middlewares = ["test-stripprefix"]
      # If the rule matches, forward to the whoami service (declared below)
      service = "whoami"
    [http.routers.user-management]
      rule = "Host(`127.0.0.1`) && PathPrefix(`/usermanagement/`)"
      #If the rule matches, applies the middleware
      middlewares = ["common-stripprefix"]
      #If the rule matches, forward to the user management service (declared below)
      service = "user-management"

  [http.middlewares]
    [http.middlewares.test-stripprefix.stripPrefix]
      prefixes = ["/", "/"]
    # Define an authentication mechanism
    [http.middlewares.test-user.basicAuth]
      users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"]
    [http.middlewares.common-stripprefix.stripPrefix]
      prefixes = ["/usermanagement", "/usermanagement/"]

  [http.services]
    # Define how to reach an existing service on our infrastructure
    [http.services.whoami.loadBalancer]
      [[http.services.whoami.loadBalancer.servers]]
        url = "http://127.0.0.1:3001/"
    #Define how to reach user management service on our infrastructure
    [http.services.user-management.loadBalancer]
      [[http.services.user-management.loadBalancer.servers]]
        url = "http://127.0.0.1:3000/"



