http:
  routers:
    webFrontend:
      entryPoints:
        - web
      rule: "Host(`admin.vaccineledger.com`) && PathPrefix(`/`)"
      service: frontend
    apiAddress:
      entryPoints:
        - http
      rule: "Host(`admin.vaccineledger.com`) && PathPrefix(`/api/address_service`)"
      service: address
    apiAffiation:
      entryPoints:
        - http    
      rule: "Host(`admin.vaccineledger.com`) && PathPrefix(`/api/affliation_service`)"
      service: affliation
    apiEmployee:
      entryPoints:
        - http    
      rule: "Host(`admin.vaccineledger.com`) && PathPrefix(`/api/employee_service`)"
      service: employee
    apiRbac:
      entryPoints:
        - http    
      rule: "Host(`admin.vaccineledger.com`) && PathPrefix(`/api/rbac_service`)"
      service: rbac 

  services:
    frontend:
      loadBalancer:
        servers:
          - url : "http://localhost:3000"
    apiAddress:
      loadBalancer:
        servers:
          - url : "http://localhost:3001"
    apiAffiation:
      loadBalancer:
        servers:
          - url : "http://localhost:3002"
    apiEmployee:
      loadBalancer:
        servers:
          - url : "http://localhost:3003"
    apiRbac:
      loadBalancer:
        servers:
          - url : "http://localhost:3004"                        