exports.constants = {
  admin: {
    name: "admin",
    email: "admin@admin.com",
  },
  confirmEmails: {
    from: "no-reply@test-app.com",
  },
};
exports.warehouseDistrictMapping = [
  {
    depot: "ATTIBELE",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1006",
  },
  {
    depot: "KOTHANUR",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1007",
  },
  {
    depot: "PLATFORM ROAD",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1008",
  },
  {
    depot: "KAMMANAHALLI",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1009",
  },
  {
    depot: "DEVANAHALLI",
    district: "BENGALURU RURAL",
    state: "Karnataka",
    warehouseId: "WAR1010",
  },
  {
    depot: "SIRA",
    district: "TUMKUR",
    state: "Karnataka",
    warehouseId: "WAR1011",
  },
  {
    depot: "TIPTUR",
    district: "TUMKUR",
    state: "Karnataka",
    warehouseId: "WAR1012",
  },
  {
    depot: "TUMAKURU",
    district: "TUMKUR",
    state: "Karnataka",
    warehouseId: "WAR1013",
  },
  {
    depot: "BANGARPET",
    district: "KOLAR",
    state: "Karnataka",
    warehouseId: "WAR1014",
  },
  {
    depot: "CHICKABALLAPUR",
    district: "CHIKBALLAPUR",
    state: "Karnataka",
    warehouseId: "WAR1015",
  },
  {
    depot: "CHINTAMANI",
    district: "CHIKBALLAPUR",
    state: "Karnataka",
    warehouseId: "WAR1016",
  },
  {
    depot: "DODDABALLAPURA",
    district: "BENGALURU RURAL",
    state: "Karnataka",
    warehouseId: "WAR1017",
  },
  {
    depot: "KENGERI",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1018",
  },
  {
    depot: "KOLAR",
    district: "KOLAR",
    state: "Karnataka",
    warehouseId: "WAR1019",
  },
  {
    depot: "RAMANAGARA",
    district: "RAMANAGARA",
    state: "Karnataka",
    warehouseId: "WAR1020",
  },
  {
    depot: "WHITE FIELD",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1021",
  },
  {
    depot: "WHITE FIELD-2",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1022",
  },
  {
    depot: "BAGALKUNTE",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1023",
  },
  {
    depot: "BAGALKUNTE-2",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1024",
  },
  {
    depot: "HONGASANDRA",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1025",
  },
  {
    depot: "KACHOHALLI",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1026",
  },
  {
    depot: "KG HALLI",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1027",
  },
  {
    depot: "MADANAYAKANAHALLI",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1028",
  },
  {
    depot: "PEENYA",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1029",
  },
  {
    depot: "SAKALAVARA-1",
    district: "BENGALURU RURAL",
    state: "Karnataka",
    warehouseId: "WAR1030",
  },
  {
    depot: "SAKALAVARA-2",
    district: "BENGALURU RURAL",
    state: "Karnataka",
    warehouseId: "WAR1031",
  },
  {
    depot: "YESHWANTHPURA",
    district: "BENGALURU URBAN",
    state: "Karnataka",
    warehouseId: "WAR1032",
  },
  {
    depot: "BAGALKOT",
    district: "BAGALKOT",
    state: "Karnataka",
    warehouseId: "WAR1033",
  },
  {
    depot: "BIDAR",
    district: "BIDAR",
    state: "Karnataka",
    warehouseId: "WAR1034",
  },
  {
    depot: "JAMAKHANDI",
    district: "BAGALKOT",
    state: "Karnataka",
    warehouseId: "WAR1035",
  },
  {
    depot: "KALABURAGI",
    district: "GULBARG",
    state: "Karnataka",
    warehouseId: "WAR1036",
  },
  {
    depot: "RAICHUR",
    district: "RAICHUR",
    state: "Karnataka",
    warehouseId: "WAR1037",
  },
  {
    depot: "SEDAM",
    district: "GULBARG",
    state: "Karnataka",
    warehouseId: "WAR1038",
  },
  {
    depot: "SINDHANUR",
    district: "RAICHUR",
    state: "Karnataka",
    warehouseId: "WAR1039",
  },
  {
    depot: "VIJAYAPURA",
    district: "BIJAPUR",
    state: "Karnataka",
    warehouseId: "WAR1040",
  },
  {
    depot: "YADHAGIRI",
    district: "YADGIR",
    state: "Karnataka",
    warehouseId: "WAR1041",
  },
  {
    depot: "BELAGAVI",
    district: "BELGAUM",
    state: "Karnataka",
    warehouseId: "WAR1042",
  },
  {
    depot: "BELAGAVI-2",
    district: "BELGAUM",
    state: "Karnataka",
    warehouseId: "WAR1043",
  },
  {
    depot: "DHARWAD",
    district: "DHARWAD",
    state: "Karnataka",
    warehouseId: "WAR1044",
  },
  {
    depot: "GOKAK",
    district: "BELGAUM",
    state: "Karnataka",
    warehouseId: "WAR1045",
  },
  {
    depot: "HARIHARA",
    district: "DAVANGERE",
    state: "Karnataka",
    warehouseId: "WAR1046",
  },
  {
    depot: "HAVERI",
    district: "HAVERI",
    state: "Karnataka",
    warehouseId: "WAR1047",
  },
  {
    depot: "HONNAVAR",
    district: "UTTARA KANNADA",
    state: "Karnataka",
    warehouseId: "WAR1048",
  },
  {
    depot: "HUBBALLI",
    district: "DHARWAD",
    state: "Karnataka",
    warehouseId: "WAR1049",
  },
  {
    depot: "SIRSI",
    district: "UTTARA KANNADA",
    state: "Karnataka",
    warehouseId: "WAR1050",
  },
  {
    depot: "BALLARI",
    district: "BELLARY",
    state: "Karnataka",
    warehouseId: "WAR1051",
  },
  {
    depot: "BHADRAVATHI",
    district: "SHIVAMOGGA",
    state: "Karnataka",
    warehouseId: "WAR1052",
  },
  {
    depot: "CHALLAKERE",
    district: "CHITRADURGA",
    state: "Karnataka",
    warehouseId: "WAR1053",
  },
  {
    depot: "CHITRADURGA",
    district: "CHITRADURGA",
    state: "Karnataka",
    warehouseId: "WAR1054",
  },
  {
    depot: "DAVANGERE",
    district: "DAVANGERE",
    state: "Karnataka",
    warehouseId: "WAR1055",
  },
  {
    depot: "GADAG",
    district: "GADAG",
    state: "Karnataka",
    warehouseId: "WAR1056",
  },
  {
    depot: "HOSAPETE",
    district: "VIJAYANAGARA",
    state: "Karnataka",
    warehouseId: "WAR1057",
  },
  {
    depot: "KOPPAL",
    district: "KOPPAL",
    state: "Karnataka",
    warehouseId: "WAR1058",
  },
  {
    depot: "SAGAR",
    district: "SHIVAMOGGA",
    state: "Karnataka",
    warehouseId: "WAR1059",
  },
  {
    depot: "SHIVAMOGGA",
    district: "SHIVAMOGGA",
    state: "Karnataka",
    warehouseId: "WAR1060",
  },
  {
    depot: "CHIKKAMAGALURU",
    district: "CHIKKAMAGALURU",
    state: "Karnataka",
    warehouseId: "WAR1061",
  },
  {
    depot: "KUNDAPURA",
    district: "UDUPI",
    state: "Karnataka",
    warehouseId: "WAR1062",
  },
  {
    depot: "MANGALURU",
    district: "DAKSHINA KANNADA",
    state: "Karnataka",
    warehouseId: "WAR1063",
  },
  {
    depot: "MANGALURU-2",
    district: "DAKSHINA KANNADA",
    state: "Karnataka",
    warehouseId: "WAR1064",
  },
  {
    depot: "PUTTUR",
    district: "DAKSHINA KANNADA",
    state: "Karnataka",
    warehouseId: "WAR1065",
  },
  {
    depot: "UDUPI",
    district: "UDUPI",
    state: "Karnataka",
    warehouseId: "WAR1066",
  },
  {
    depot: "CHAMARAJANAGAR",
    district: "CHAMARAJANAGAR",
    state: "Karnataka",
    warehouseId: "WAR1067",
  },
  {
    depot: "HASSAN",
    district: "HASSAN",
    state: "Karnataka",
    warehouseId: "WAR1068",
  },
  {
    depot: "HASSAN-2",
    district: "HASSAN",
    state: "Karnataka",
    warehouseId: "WAR1069",
  },
  {
    depot: "HUNSUR",
    district: "MYSURU",
    state: "Karnataka",
    warehouseId: "WAR1070",
  },
  {
    depot: "KUSHALNAGAR",
    district: "KODAGU",
    state: "Karnataka",
    warehouseId: "WAR1071",
  },
  {
    depot: "MANDYA",
    district: "MANDYA",
    state: "Karnataka",
    warehouseId: "WAR1072",
  },
  {
    depot: "MYSURU BANNIMANTAP",
    district: "MYSURU",
    state: "Karnataka",
    warehouseId: "WAR1073",
  },
  {
    depot: "MYSURU HEBBAL",
    district: "MYSURU",
    state: "Karnataka",
    warehouseId: "WAR1074",
  },
  {
    depot: "PANDAVAPURA",
    district: "MANDYA",
    state: "Karnataka",
    warehouseId: "WAR1075",
  },
  {
    depot: "VIRAJPET",
    district: "KODAGU",
    state: "Karnataka",
    warehouseId: "WAR1076",
  },
];
