export const GET_INVENTORIES_SUCCESS = "GET_INVENTORIES_SUCCESS";
export const GET_INVENTORIES_FAILURE = "GET_INVENTORIES_FAILURE";
export const SET_REVIEW_INVENTORY = "SET_REVIEW_INVENTORY";
export const GET_INVENTORIESCOUNT_SUCCESS = "GET_INVENTORIESCOUNT_SUCCESS";
export const GET_INVENTORIESCOUNT_FAILURE = "GET_INVENTORIESCOUNT_FAILURE";
export const SET_EDIT_INVENTORY = "SET_EDIT_INVENTORY";
export const RESET_EDIT_INVENTORY = "RESET_EDIT_INVENTORY";
export const RESET_REVIEW_INVENTORY = "RESET_REVIEW_INVENTORY";

export const SET_AFFILIATED_PENDING_REQUESTS =
  "SET_AFFILIATED_PENDING_REQUESTS";
export const SET_PERMISSIONS = "SET_PERMISSIONS";
export const SET_ORGANISATION_ADDRESSES = "SET_ORGANISATION_ADDRESSES";
export const GET_FAILURE = "GET_FAILURE";
export const SET_ORGANISATION_USERS = "SET_ORGANISATION_USERS";
export const SET_ORGANISATION_REQ_SENT = "SET_ORGANISATION_REQ_SENT";
export const SET_AFFILATED_PENDING_REQ = "SET_AFFILATED_PENDING_REQ";
export const SET_AFFILATED_ORGS = "SET_AFFILATED_ORGS";
