export const SET_AFFILIATED_PENDING_REQUESTS =
  "SET_AFFILIATED_PENDING_REQUESTS";
export const SET_PERMISSIONS = "SET_PERMISSIONS";
export const SET_ORGANISATION_ADDRESSES = "SET_ORGANISATION_ADDRESSES";
export const GET_FAILURE = "GET_FAILURE";
export const SET_ORGANISATION_USERS = "SET_ORGANISATION_USERS";
export const SET_ORGANISATION_REQ_SENT = "SET_ORGANISATION_REQ_SENT";
export const SET_AFFILATED_PENDING_REQ = "SET_AFFILATED_PENDING_REQ";
export const SET_AFFILATED_ORGS = "SET_AFFILATED_ORGS";
export const SET_ORGANISATIONS = "SET_ORGANISATIONS";
