export const SERVER_URL = process.env.REACT_APP_SERVER_URL || "https://test.vaccineledger.com";
export const LOCAL_SERVER_URL_USER = "//localhost:3001";
export const LOCAL_SERVER_URL_ADDRESS = "//localhost:3001";
export const LOCAL_SERVER_URL_AFFILIATION = "//localhost:3002";
export const LOCAL_SERVER_URL_EMPLOYEE = "//localhost:3003";
export const LOCAL_SERVER_URL_RBAC = "//localhost:3004";
export const LOCAL_SERVER_URL_CONFIG = "//localhost:3005";

export function config() {
  const confs = {
    local: {
      sendOtpUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/auth/sendOtp`,
      verifyOtpUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/auth/verifyOtp`,
      getApprovalsUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/getApprovals`,
      getPermissionsUrl: `${LOCAL_SERVER_URL_RBAC}/api/rbac_service/getPermissions`,
      getWareHousesUrl: `${LOCAL_SERVER_URL_ADDRESS}/api/address_service/fetchWarehouses`,
      fetchWarehousesByOrgId: `${LOCAL_SERVER_URL_ADDRESS}/api/address_service/fetchWarehousesByOrgId`,
      getWarehouseAndUsersById: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/getWarehouseAndUsersById`,
      verifyOrgUserUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/acceptApproval`,
      updateOrgUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/updateOrg`,
      rejectOrgUserUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/rejectApproval`,
      activateOrgUserUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/activateUser`,
      deactivateOrgUserUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/deactivateUser`,
      getOrgUsersUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/auth/getOrgUsers`,
      addOrgsFromExcel: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/auth/addOrgsFromExcel`,
      addUsersFromExcel: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/auth/addUsersFromExcel`,
      getWarehouseUsers: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/auth/getWarehouseUsers`,
      getOrgsUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/getOrgs`,
      getOrgDetails: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/getOrgDetails`,
      getOrgAnalytics: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/getOrgAnalytics`,
      getOrgUserAnalytics: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/auth/getOrgUserAnalytics`,
      getOrgActiveUsers: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/auth/getOrgActiveUsers`,
      addOrgUserUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/addUser`,
      updateUserRole: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/updateUserRole`,
      addNewOrganisation: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/addNewOrganisation`,
      getPendingOrgs: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/getPendingOrgs`,
      recentRequestsSentUrl: `${LOCAL_SERVER_URL_AFFILIATION}/api/affliation_service/fetchSentRequests`,
      userInfoUrl: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/auth/userInfo`,
      pendingAffiliatedReqUrl: `${LOCAL_SERVER_URL_AFFILIATION}/api/affliation_service/fetchPendingRequests`,
      affiliatedOrgUrl: `${LOCAL_SERVER_URL_AFFILIATION}/api/affliation_service/fetchAffiliates`,
      getAllOrgUrl: `${LOCAL_SERVER_URL_AFFILIATION}/api/affliation_service/getAllOrg`,
      unaffiliateUserUrl: `${LOCAL_SERVER_URL_AFFILIATION}/api/affliation_service/unAffiliate`,
      unaffiliateOrgUrl: `${LOCAL_SERVER_URL_AFFILIATION}/api/affliation_service/unAffiliateOrg`,
      acceptAffiliateUrl: `${LOCAL_SERVER_URL_AFFILIATION}/api/affliation_service/acceptAffiliate`,
      rejectAffiliateUrl: `${LOCAL_SERVER_URL_AFFILIATION}/api/affliation_service/rejectAffiliate`,
      addAffiliateUrl: `${LOCAL_SERVER_URL_AFFILIATION}/api/affliation_service/addAffiliate`,
      addOrgAddressrUrl: `${LOCAL_SERVER_URL_ADDRESS}/api/address_service/addWarehouse`,
      getLocationApprovalUrl: `${LOCAL_SERVER_URL_ADDRESS}/api/address_service/getLocationApprovals`,
      updateOrgAddressrUrl: `${LOCAL_SERVER_URL_ADDRESS}/api/address_service/updateWarehouse`,
      addAddressesFromExcelUrl: `${LOCAL_SERVER_URL_ADDRESS}/api/address_service/addAddressesFromExcel`,
      modifyLocationUrl: `${LOCAL_SERVER_URL_ADDRESS}/api/address_service/modifyLocation`,
      getOrgTypesUrl: `${LOCAL_SERVER_URL_ADDRESS}/api/configuration_service/getOrganizationsByType?id=CONF000`,
      getOrgTypeiIdsUrl: `${LOCAL_SERVER_URL_ADDRESS}/api/configuration_service/getOrganizationsByType?id=`,
      updateOrgTypesUrl: `${LOCAL_SERVER_URL_ADDRESS}/api/configuration_service/updateOrganizationsByType`,
      addNewOrgTypesUrl: `${LOCAL_SERVER_URL_ADDRESS}/api/configuration_service/addNewOrgType`,
      imgDomainUrl: `${SERVER_URL}`,
      getCountryDataUrl: `${SERVER_URL}/api/address_service/getCountries`,
      getRegionDataUrl: `${SERVER_URL}/api/address_service/getRegions`,
      fetchAllRoles: `${SERVER_URL}/api/rbac_service/getRoles`,
      fetchPermissionsByRole: `${SERVER_URL}/api/rbac_service/getPermissions`,
      updatePermissions: `${SERVER_URL}/api/rbac_service/updatePermissions`,
      fetchAllRegions: `${SERVER_URL}/productmanagement/api/location?region=all`,
      fetchCountriesByRegion: `${SERVER_URL}/productmanagement/api/location?region=`,
      fetchStateByCountry: `${SERVER_URL}/productmanagement/api/location?country_id=`,
      fetchCitiesByState: `${SERVER_URL}/productmanagement/api/location?state_id=`,
    },
    prod: {
      imgDomainUrl: `${SERVER_URL}`,
      sendOtpUrl: `${SERVER_URL}/api/employee_service/auth/sendOtp`,
      verifyOtpUrl: `${SERVER_URL}/api/employee_service/auth/verifyOtp`,
      getApprovalsUrl: `${SERVER_URL}/api/employee_service/getApprovals`,
      getPermissionsUrl: `${SERVER_URL}/api/rbac_service/getPermissions`,
      getWareHousesUrl: `${SERVER_URL}/api/address_service/fetchWarehouses`,
      fetchWarehousesByOrgId: `${SERVER_URL}/api/address_service/fetchWarehousesByOrgId`,
      getWarehouseAndUsersById: `${SERVER_URL}/api/employee_service/getWarehouseAndUsersById`,
      updateOrgUrl: `${SERVER_URL}/api/employee_service/updateOrg`,
      verifyOrgUserUrl: `${SERVER_URL}/api/employee_service/acceptApproval`,
      rejectOrgUserUrl: `${SERVER_URL}/api/employee_service/rejectApproval`,
      activateOrgUserUrl: `${SERVER_URL}/api/employee_service/activateUser`,
      deactivateOrgUserUrl: `${SERVER_URL}/api/employee_service/deactivateUser`,
      getOrgUsersUrl: `${SERVER_URL}/api/employee_service/auth/getOrgUsers`,
      addOrgsFromExcel: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/auth/addOrgsFromExcel`,
      addUsersFromExcel: `${SERVER_URL}/api/employee_service/auth/addUsersFromExcel`,
      getOrgsUrl: `${SERVER_URL}/api/employee_service/getOrgs`,
      getOrgDetails: `${SERVER_URL}/api/employee_service/getOrgDetails`,
      getOrgAnalytics: `${SERVER_URL}/api/employee_service/getOrgAnalytics`,
      getOrgUserAnalytics: `${SERVER_URL}/api/employee_service/auth/getOrgUserAnalytics`,
      getWarehouseUsers: `${SERVER_URL}/api/employee_service/auth/getWarehouseUsers`,
      getOrgActiveUsers: `${SERVER_URL}/api/employee_service/auth/getOrgActiveUsers`,
      addOrgUserUrl: `${SERVER_URL}/api/employee_service/addUser`,
      updateUserRole: `${SERVER_URL}/api/employee_service/updateUserRole`,
      addNewOrganisation: `${LOCAL_SERVER_URL_EMPLOYEE}/api/employee_service/addNewOrganisation`,
      getPendingOrgs: `${SERVER_URL}/api/employee_service/getPendingOrgs`,
      recentRequestsSentUrl: `${SERVER_URL}/api/affliation_service/fetchSentRequests`,
      userInfoUrl: `${SERVER_URL}/api/employee_service/auth/userInfo`,
      pendingAffiliatedReqUrl: `${SERVER_URL}/api/affliation_service/fetchPendingRequests`,
      affiliatedOrgUrl: `${SERVER_URL}/api/affliation_service/fetchAffiliates`,
      getAllOrgUrl: `${SERVER_URL}/api/affliation_service/getAllOrg`,
      unaffiliateUserUrl: `${SERVER_URL}/api/affliation_service/unAffiliate`,
      unaffiliateOrgUrl: `${SERVER_URL}/api/affliation_service/unAffiliateOrg`,
      acceptAffiliateUrl: `${SERVER_URL}/api/affliation_service/acceptAffiliate`,
      rejectAffiliateUrl: `${SERVER_URL}/api/affliation_service/rejectAffiliate`,
      addOrgAddressrUrl: `${SERVER_URL}/api/address_service/addWarehouse`,
      addAffiliateUrl: `${SERVER_URL}/api/affliation_service/addAffiliate`,
      updateOrgAddressrUrl: `${SERVER_URL}/api/address_service/updateWarehouse`,
      addAddressesFromExcelUrl: `${SERVER_URL}/api/address_service/addAddressesFromExcel`,
      getOrgTypesUrl: `${SERVER_URL}/api/configuration_service/getOrganizationsByType?id=CONF000`,
      getOrgTypeiIdsUrl: `${SERVER_URL}/api/configuration_service/getOrganizationsByType?id=`,
      updateOrgTypesUrl: `${SERVER_URL}/api/configuration_service/updateOrganizationsByType`,
      addNewOrgTypesUrl: `${SERVER_URL}/api/configuration_service/addNewOrgType`,
      getLocationApprovalUrl: `${SERVER_URL}/api/address_service/getLocationApprovals`,
      modifyLocationUrl: `${SERVER_URL}/api/address_service/modifyLocation`,
      getCountryDataUrl: `${SERVER_URL}/api/address_service/getCountries`,
      getRegionDataUrl: `${SERVER_URL}/api/address_service/getRegions`,
      fetchAllRoles: `${SERVER_URL}/api/rbac_service/getRoles`,
      fetchPermissionsByRole: `${SERVER_URL}/api/rbac_service/getPermissions`,
      updatePermissions: `${SERVER_URL}/api/rbac_service/updatePermissions`,
      fetchAllRegions: `${SERVER_URL}/productmanagement/api/location?region=all`,
      fetchCountriesByRegion: `${SERVER_URL}/productmanagement/api/location?region=`,
      fetchStateByCountry: `${SERVER_URL}/productmanagement/api/location?country_id=`,
      fetchCitiesByState: `${SERVER_URL}/productmanagement/api/location?state_id=`,
    },
  };

  const environment = process.env.REACT_APP_ENVIRONMENT || "prod"; // change prod to test, local,stable, dev for respective environments
  const conf = confs[environment];

  return conf;
}
