apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: analytics-feed
  name: analytics-feed
spec:
  replicas: 1 
  selector:
    matchLabels:
      k8s-app: analytics-feed
  strategy: {}
  template:
    metadata:
      labels:
        k8s-app: analytics-feed
    spec:
      containers:
        - image: dockerhub/analytics_feed:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
          name: analytics-feed
          envFrom:
            - configMapRef:
                name: divoc-config
      restartPolicy: Always
status: {}
