apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-feed
  namespace: divoc
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-feed
  targetCPUUtilizationPercentage: 70