apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    k8s-app: digilocker-support-api
  name: digilocker-support-api
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: "tcp-8003"
      port: 8003
      protocol: TCP
      targetPort: 8003
  selector:
    k8s-app: digilocker-support-api
  sessionAffinity: None
  type: LoadBalancer