apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    k8s-app: keycloak-service
  name: keycloak-service
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: "tcp-8003"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s-app: keycloak-service
  sessionAffinity: None
  type: LoadBalancer