apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    k8s-app: registry
  name: registry
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    k8s-app: registry
status:
  loadBalancer: {}

