[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$eMYDuZHm$/q83sXxYLLD1cnbbskfC.0"
  ]

[http.routers.api]
  # rule = "Host(`admin.vaccineledger.com`) && PathPrefix(`/admin`)"
  rule = "PathPrefix(`/admin)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"