## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  webapi:
    address: ":9000"  

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
# certificatesResolvers:
#   lets-encr:
#     acme:
#       #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
#       storage: acme.json
#       email: ashwini@statwig.com
#       httpChallenge:
#         entryPoint: web
         