export const TEST_SERVER_URL = 'https://test.vaccineledger.com';
export const TEST_SERVER_URL_FOR_ROAMBEE = "https://integrations.vaccineledger.com";
export const PROD_SERVER_URL = 'https://vaccineledger.com';
export const ABINBEVPROD_SERVER_URL = 'https://abinbev.statledger.io';
export const ABINBEVTEST_SERVER_URL = 'https://test.abinbev.statledger.io';
export const UNICEFTEST_SERVER_URL = 'https://unicef.vaccineledger.com';
export const LOCAL_SERVER_URL_USER = 'http://localhost:3001';
export const LOCAL_SERVER_URL_SHIPPINGORDER ='http://localhost:3013';
export const LOCAL_SERVER_URL_SHIPMENT = 'http://localhost:3002';
export const LOCAL_SERVER_URL_INVENTORY = 'http://localhost:3007';
export const LOCAL_SERVER_URL_PO = 'http://localhost:3012';
export const LOCAL_SERVER_URL_TRACKANDTRACE = 'http://localhost:3005';
export const LOCAL_SERVER_URL_NOTIFICATION = 'http://localhost:3006';
export const LOCAL_SERVER_URL_ANALYTICS = 'http://localhost:3015';
export const LOCAL_SERVER_URL_EOL = 'http://localhost:3017';
export const LOCAL_SERVER_URL_EVENT = 'http://localhost:3014';
export const LOCAL_SERVER_URL_PRODUCTS = 'http://localhost:3010';
export const LOCAL_SERVER_URL_ALERTS = 'http://localhost:3004';

/*Shipping order URL needs to be updated for stable server*/ 

export function config() {
  const confs = {
    local: {
      getOrganizationsUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getOrganizations?orgType=`,
      loginUrl: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/login`,
      sendOtpUrl: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/sendOtp`,
      registerUrl: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/register`,
      checkUserUrl: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/check`,
      verifyOtpUrl: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/verifyOtp`,
      userInfoUrl: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/userInfo`,
      getAllUsersUrl: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/getAllUsers`,
      updateProfileUrl: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/updateProfile`,
      locationUrl: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/switchLocation`,
      upload: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/uploadImage?`,
      fetchProfileImage:`${LOCAL_SERVER_URL_USER}`,
      uploadProfileImage:`${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/uploadImage?action=PROFILE`,
      getOrganizationsByTypeUrl: `${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/getOrganizationsByType?id=`,
      getAnalyticsUrl:`${LOCAL_SERVER_URL_ANALYTICS}/analyticsmanagement/api/analytics/getAnalytics`,
      getOverviewAnalyticsUrl:`${LOCAL_SERVER_URL_ANALYTICS}/analyticsmanagement/api/analytics/getOverviewAnalytics`,
      getInventoryAnalyticsUrl:`${LOCAL_SERVER_URL_ANALYTICS}/analyticsmanagement/api/analytics/getInventoryAnalytics`,
      getShipmentAnalyticsUrl:`${LOCAL_SERVER_URL_ANALYTICS}/analyticsmanagement/api/analytics/getShipmentAnalytics`,
      getOrderAnalyticsUrl:`${LOCAL_SERVER_URL_ANALYTICS}/analyticsmanagement/api/analytics/getOrderAnalytics`,
      createShippingOrderUrl:`${LOCAL_SERVER_URL_SHIPPINGORDER}/shippingordermanagement/api/shipping/createShippingOrder`,
      getShippingOrdersUrl:`${LOCAL_SERVER_URL_SHIPPINGORDER}/shippingordermanagement/api/shipping/getShippingOrders`,
      getShippingOrderIdsUrl:`${LOCAL_SERVER_URL_SHIPPINGORDER}/shippingordermanagement/api/shipping/getShippingOrderIds`,
      viewShippingOrderUrl:`${LOCAL_SERVER_URL_SHIPPINGORDER}/shippingordermanagement/api/shipping/viewShippingOrder?soId=`,
      shipmentsUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/fetchShipments`,
      viewShipmentUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/viewShipment?shipmentId=`,
      getShipmentIdsUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/fetchShipmentIds`,
      chainOfCustody: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/chainOfCustody?shipmentId=`,
      receiveApi: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/receiveShipment`,
      uploadImage: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/uploadImage?id=`,
      fetchImage: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/fetchImage?id=`,    
      getImage: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment`,            
      getProducts: `${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/products/getProducts`,
      getProductsByCategoryUrl: `${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/products/getProductsByCategory?type=`,
      getProductsByInventoryUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/getProductsByInventory?invId=`,
      generateCodes: `${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/products/generateCodes`,
      getManufacturers: `${LOCAL_SERVER_URL_SHIPMENT}/productmanagement/api/products/getManufacturer`,
      getSerialNumbersByBatchNumber: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getInventoryDetailsByBatchNumber?skip=0&limit=100&batchNumber=`,
      getInventoryDetailsUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getInventoryDetails`,
      getInventoryByBatchNumber:`${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getBatchDetailsByBatchNumber?skip=0&limit=100&batchNumber=`,
      addProductsToInventory: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/addProductsToInventory`,
      addInventoriesFromExcel: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/addInventoriesFromExcel`,
      createShipmentUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/createShipment`,
      addInventoryUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/addNewInventory`,
      shipmentsSearch: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipping/fetchShipments?key=`,
      inventorySearch: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getInventoryDetailsForProduct?key=`,
      getProductDetailsByWarehouseIdUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getProductDetailsByWarehouseId?warehouseId=`,
      getRegionsUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getRegions`,
      getCountryByRegionUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getCountryDetailsByRegion?region=`,
      getWareHousesByCountryUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getWarehouseDetailsByCountry?name=`,
      getWareHousesByRegionUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getWarehouseDetailsByRegion?region=`,
      createPurchaseOrderUrl: `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/createPurchaseOrder`,
      createOrderUrl: `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/createOrder`,
      fetchPurchaseOrderUrl: `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/fetchPurchaseOrders`,
      fetchPurchaseOrderById: `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/fetchPurchaseOrders?skip=0&limit=5&poId=`,
      productListUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getProductListCounts`,
      inventoriesUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getInventory`,
      bacthcNearExpiryUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getBatchNearExpiration`,
      batchExpiredUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getBatchExpired`,
      batchWarehouseUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getBatchWarehouse`,
      addPOsFromExcelUrl: `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/addPOsFromExcel`,
      changePOStatus: `${LOCAL_SERVER_URL_SHIPMENT}/pomanagement/api/po/changePOStatus`,
      fetchAllPurchaseOrderUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipping/fetchpurchaseOrder?key=`,
      getPOsUrl: `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/purchaseOrderStatistics`,
      trackShipment: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipping/trackShipment?shipmentId=`,
      trackShipmentJourney: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/trackJourney?trackingId=`,
      trackJourney: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/trackJourney?trackingId=`,
      poDetailsByShipmentId:`${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipping/fetchPOdetailsByShipmentID?shipmentId=`,
      productDetailsByShipmentId:`${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipping/fetchProductdetailsByShipmentID?shipmentId=`,
      trackTemperature: `${LOCAL_SERVER_URL_TRACKANDTRACE}/tracktracemanagement/api/track/fetchTemp`,
      trackProduct: `${LOCAL_SERVER_URL_TRACKANDTRACE}/tracktracemanagement/api/track/track?trackingNumber=`,
      addNewProduct: `${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/products/addProduct`,
      getOrganisations:`${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/organisation/getOrganisations`,
      getWarehouseByOrgId:`${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/organisation/warehouses?id=`,
      getAllWarehouses:`${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/organisation/allWarehouses`,
      addMultipleProducts: `${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/products/addMultipleProducts`,
      getNotificationsUrl: `${LOCAL_SERVER_URL_NOTIFICATION}/notificationmanagement/api/notification/getNotifications`,
      deleteNotificationUrl: `${LOCAL_SERVER_URL_NOTIFICATION}/notificationmanagement/api/notification/deleteNotification`,
      updateTrackingStatusUrl:`${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/updateTrackingStatus`,
      getOrderIds:`${LOCAL_SERVER_URL_PO}/pomanagement/api/po/getOrderIds`,
      getOpenOrderIds:`${LOCAL_SERVER_URL_PO}/pomanagement/api/po/getOpenOrderIds`,
      fetchOutboundPurchaseOrderUrl: `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/fetchOutboundPurchaseOrders`,
      fetchInboundPurchaseOrderUrl: `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/fetchInboundPurchaseOrders`,
      getOrganizationsByType:`${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/getOrganizationsByType?id=`,
      getwarehouseByType:`${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/getwarehouseByType?id=`,
      fetchProductIdsCustomerLocationsOrganisationsUrl: `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/fetchProductIdsCustomerLocationsOrganisations`,
      fetchInboundShipmentsUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/fetchInboundShipments`,
      fetchOutboundShipmentsUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/fetchOutboundShipments`,
      GetEOLInfoBySerialNumber:`${LOCAL_SERVER_URL_EOL}/lastmilemanagement/api/GetEOLInfoBySerialNumber?serial_number=`,
      GetEOLInfoByProductId:`${LOCAL_SERVER_URL_EOL}/lastmilemanagement/api/GetEOLInfoByProductId?id=`,
      GetEOLInfoByIdentityId:`${LOCAL_SERVER_URL_EOL}/lastmilemanagement/api/GetEOLInfoByIdentityId?id=`,
      GetEOLInfoByPlaceAdministered:`${LOCAL_SERVER_URL_EOL}/lastmilemanagement/api/GetEOLInfoByPlaceAdministered?place=`,
      GetEOLListByDateWindow:`${LOCAL_SERVER_URL_EOL}/lastmilemanagement/api/GetEOLListByDateWindow`,
      fetchSupplierAndReceiverListUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/fetchSupplierAndReceiverList`,
      updateWarehouse: `${LOCAL_SERVER_URL_SHIPMENT}/usermanagement/api/auth/updateWarehouse?warehouseId=`,
      getWarehouseById: `${LOCAL_SERVER_URL_SHIPMENT}/usermanagement/api/auth/getwarehouseinfo?id=`,
      addPOsFromExcel:`${LOCAL_SERVER_URL_PO}/pomanagement/api/po/addPOsFromExcel`,
      getOrganizationsTypewithauth:`${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/getOrganizationsTypewithauth?id=`,
      getTransactions: `${LOCAL_SERVER_URL_EVENT}/eventmanagement/api/event/getAllEventsWithFilter`,
      getTransactionFilterList: `${LOCAL_SERVER_URL_EVENT}/eventmanagement/api/event/fetchProductDetailsList`,
      getRegionsUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getRegions`,
      getCountryByRegionUrl: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getCountryDetailsByRegion?region=`,
      getAllStates: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getAllStates`,
      getDistrictsByState: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getDistrictsByState`,
      GetEOLInfo:`${LOCAL_SERVER_URL_EOL}/lastmilemanagement/api/GetEOLInfo`,
      GetProductsByWarehouse:`${LOCAL_SERVER_URL_EOL}/lastmilemanagement/api/getProductsByWarehouse`,
      getCountries: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getCountries`,
      getStatesByCountry: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getStatesByCountry`,
      getCitiesByState: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getCitiesByState`,
      getWarehousesByCity: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getWarehousesByCity`,
      emailverify:`${LOCAL_SERVER_URL_USER}/usermanagement/api/auth/emailverify`,
      fetchairwayBillNumber:`${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/fetchairwayBillNumber`,
      fetchAllRegions:`${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/location?region=all`,
      fetchCountriesByRegion:`${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/location?region=`,
      fetchStateByCountry:`${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/location?country_id=`,
      fetchCitiesByState:`${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/location?state_id=`,
      getIotEnabledStatus:`${LOCAL_SERVER_URL_PRODUCTS}/productmanagement/api/products/getIotEnabledStatus`,
      trackLastTenIotShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/lastteniotsamplesforshipmentid/:shipmentId`,
      trackLatestShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/latestiotdataforshipmentid/:shipmentId`,
      trackAllIotShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/alliotsamplesforshipmentid/:shipmentId`,
      searchProduct:`${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/searchProduct?skip=0&limit=10`,
      getSuggestions:`${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/getsearchsuggestions`,
      fetchBatchesOfInventory: `${LOCAL_SERVER_URL_INVENTORY}/inventorymanagement/api/inventory/fetchBatchesOfInventory`,
      getAlerts: `${LOCAL_SERVER_URL_ALERTS}/alertmanagement/api/alert/getAlertNotifications?type=`,
      getExportFileForInboundShipmentUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/exportInboundShipments`,
      getExportFileForOutboundShipmentUrl: `${LOCAL_SERVER_URL_SHIPMENT}/shipmentmanagement/api/shipment/exportOutboundShipment`,
      getExportFileForInboundPurchaseOrdersUrl: `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/exportInboundPurchaseOrders`,
      getExportFileForOutboundPurchaseOrdersUrl:  `${LOCAL_SERVER_URL_PO}/pomanagement/api/po/exportOutboundPurchaseOrders`
},
    test: {
      getOrganizationsUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getOrganizations?orgType=`,
      getOrganizationsByTypeUrl: `${TEST_SERVER_URL}/usermanagement/api/auth/getOrganizationsByType?id=`,
      loginUrl: `${TEST_SERVER_URL}/usermanagement/api/auth/login`,
      sendOtpUrl: `${TEST_SERVER_URL}/usermanagement/api/auth/sendOtp`,
      registerUrl: `${TEST_SERVER_URL}/usermanagement/api/auth/register`,
      checkUserUrl: `${TEST_SERVER_URL}/usermanagement/api/auth/check`,
      verifyOtpUrl: `${TEST_SERVER_URL}/usermanagement/api/auth/verifyOtp`,
      userInfoUrl: `${TEST_SERVER_URL}/usermanagement/api/auth/userInfo`,
      getAllUsersUrl: `${TEST_SERVER_URL}/usermanagement/api/auth/getAllUsers`,
      locationUrl: `${TEST_SERVER_URL}/usermanagement/api/auth/switchLocation`,
      updateProfileUrl: `${TEST_SERVER_URL}/usermanagement/api/auth/updateProfile`,
      upload: `${TEST_SERVER_URL}/usermanagement/api/auth/uploadImage?`,
      getOrganizationsByType:`${TEST_SERVER_URL}/usermanagement/api/auth/getOrganizationsByType?id=`,
      fetchProfileImage:`${TEST_SERVER_URL}`,
      uploadProfileImage:`${TEST_SERVER_URL}/usermanagement/api/auth/uploadImage?action=PROFILE`,
      getAnalyticsUrl:`${TEST_SERVER_URL}/analyticsmanagement/api/analytics/getAnalytics`,
      getOverviewAnalyticsUrl:`${TEST_SERVER_URL}/analyticsmanagement/api/analytics/getOverviewAnalytics`,
      getInventoryAnalyticsUrl:`${TEST_SERVER_URL}/analyticsmanagement/api/analytics/getInventoryAnalytics`,
      getShipmentAnalyticsUrl:`${TEST_SERVER_URL}/analyticsmanagement/api/analytics/getShipmentAnalytics`,
      getOrderAnalyticsUrl:`${TEST_SERVER_URL}/analyticsmanagement/api/analytics/getOrderAnalytics`,
      shipmentsUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchShipments`,
      viewShipmentUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/viewShipment?shipmentId=`,
      chainOfCustody: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/chainOfCustody?shipmentId=`, 
      receiveApi: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/receiveShipment`,
      getShipmentIdsUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchShipmentIds`,
      fetchImage: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchImage?id=`, 
      getImage: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment`,  
      uploadImage: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/uploadImage?id=`,                  
      getManufacturers: `${TEST_SERVER_URL}/productmanagement/api/products/getManufacturer`,
      createShippingOrderUrl:`${TEST_SERVER_URL}/shippingordermanagement/api/shipping/createShippingOrder`,
      getShippingOrdersUrl:`${TEST_SERVER_URL}/shippingordermanagement/api/shipping/getShippingOrders`,
      getShippingOrderIdsUrl:`${TEST_SERVER_URL}/shippingordermanagement/api/shipping/getShippingOrderIds`,
      viewShippingOrderUrl:`${TEST_SERVER_URL}/shippingordermanagement/api/shipping/viewShippingOrder?soId=`,
      createShipmentUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/createShipment`,
      shipmentsSearch: `${TEST_SERVER_URL}/shipmentmanagement/api/shipping/fetchShipments?key=`,
      createPurchaseOrderUrl: `${TEST_SERVER_URL}/pomanagement/api/po/createPurchaseOrder`,
      createOrderUrl: `${TEST_SERVER_URL}/pomanagement/api/po/createOrder`,
      fetchPurchaseOrderUrl: `${TEST_SERVER_URL}/pomanagement/api/po/fetchPurchaseOrders`,
      fetchPurchaseOrderById: `${TEST_SERVER_URL}/pomanagement/api/po/fetchPurchaseOrders?skip=0&limit=5&poId=`,
      changePOStatus: `${TEST_SERVER_URL}/pomanagement/api/po/changePOStatus`,
      fetchAllPurchaseOrderUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipping/fetchpurchaseOrder?key=`,
      getPOsUrl: `${TEST_SERVER_URL}/pomanagement/api/po/purchaseOrderStatistics`,
      inventoriesUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getInventory`,
      bacthcNearExpiryUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getBatchNearExpiration`,
      batchExpiredUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getBatchExpired`,
      batchWarehouseUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getBatchWarehouse`,
      inventorySearch: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getInventoryDetailsForProduct?key=`,
      getSerialNumbersByBatchNumber: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getInventoryDetailsByBatchNumber?skip=0&limit=100&batchNumber=`,
      getInventoryDetailsUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getInventoryDetails`,
      getInventoryByBatchNumber:`${TEST_SERVER_URL}/inventorymanagement/api/inventory/getBatchDetailsByBatchNumber?skip=0&limit=100&batchNumber=`,
      addProductsToInventory: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/addProductsToInventory`,
      addInventoriesFromExcel: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/addInventoriesFromExcel`,
      addInventoryUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/addNewInventory`,
      productListUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getProductListCounts`,
      getProductDetailsByWarehouseIdUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getProductDetailsByWarehouseId?warehouseId=`,
      getRegionsUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getRegions`,
      getCountryByRegionUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getCountryDetailsByRegion?region=`,
      getWareHousesByCountryUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getWarehouseDetailsByCountry?country=`,
      getWarehouseDetailsByCountryUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getWarehouseDetailsByCountry?name=`,
      getWareHousesByRegionUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getWarehouseDetailsByRegion?region=`,
      trackShipment: `${TEST_SERVER_URL}/shipmentmanagement/api/shipping/trackShipment?shipmentId=`,
      trackShipmentJourney: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/trackJourney?trackingId=`,
      trackJourney: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/trackJourney?trackingId=`,
      poDetailsByShipmentId:`${TEST_SERVER_URL}/shipmentmanagement/api/shipping/fetchPOdetailsByShipmentID?shipmentId=`,
      productDetailsByShipmentId:`${TEST_SERVER_URL}/shipmentmanagement/api/shipping/fetchProductdetailsByShipmentID?shipmentId=`,
      trackTemperature: `${TEST_SERVER_URL}/tracktracemanagement/api/track/fetchTemp`,
      getIotEnabledStatus:`${TEST_SERVER_URL}/productmanagement/api/products/getIotEnabledStatus`,
      trackLastTenIotShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/lastteniotsamplesforshipmentid/:shipmentId`,
      trackLatestShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/latestiotdataforshipmentid/:shipmentId`,
      trackAllIotShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/alliotsamplesforshipmentid/:shipmentId`,
      trackProduct: `${TEST_SERVER_URL}/tracktracemanagement/api/track/track?trackingNumber=`,
      getOrganisations:`${TEST_SERVER_URL}/productmanagement/api/organisation/getOrganisations`,
      getOrganizationsByType:`${TEST_SERVER_URL}/usermanagement/api/auth/getOrganizationsByType?id=`,
      getwarehouseByType:`${TEST_SERVER_URL}/usermanagement/api/auth/getwarehouseByType?id=`,
      getWarehouseByOrgId:`${TEST_SERVER_URL}/productmanagement/api/organisation/warehouses?id=`,
      getAllWarehouses:`${TEST_SERVER_URL}/productmanagement/api/organisation/allWarehouses`,
      addNewProduct: `${TEST_SERVER_URL}/productmanagement/api/products/addProduct`,
      getProducts: `${TEST_SERVER_URL}/productmanagement/api/products/getProducts`,
      getProductsByCategoryUrl: `${TEST_SERVER_URL}/productmanagement/api/products/getProductsByCategory?type=`,
      getProductsByInventoryUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/getProductsByInventory?invId=`,
      generateCodes: `${TEST_SERVER_URL}/productmanagement/api/products/generateCodes`,
      addMultipleProducts: `${TEST_SERVER_URL}/productmanagement/api/products/addMultipleProducts`,
      getNotificationsUrl: `${TEST_SERVER_URL}/notificationmanagement/api/notification/getNotifications`,
      deleteNotificationUrl: `${TEST_SERVER_URL}/notificationmanagement/api/notification/deleteNotification`,
      updateTrackingStatusUrl:`${TEST_SERVER_URL}/shipmentmanagement/api/shipment/updateTrackingStatus`,
      getOrderIds:`${TEST_SERVER_URL}/pomanagement/api/po/getOrderIds`,
      getOpenOrderIds:`${TEST_SERVER_URL}/pomanagement/api/po/getOpenOrderIds`,
      fetchOutboundPurchaseOrderUrl: `${TEST_SERVER_URL}/pomanagement/api/po/fetchOutboundPurchaseOrders`,
      fetchInboundPurchaseOrderUrl: `${TEST_SERVER_URL}/pomanagement/api/po/fetchInboundPurchaseOrders`,
      fetchProductIdsCustomerLocationsOrganisationsUrl: `${TEST_SERVER_URL}/pomanagement/api/po/fetchProductIdsCustomerLocationsOrganisations`,
      fetchInboundShipmentsUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchInboundShipments`,
      fetchOutboundShipmentsUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchOutboundShipments`,
      fetchSupplierAndReceiverListUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchSupplierAndReceiverList`,
      updateWarehouse: `${TEST_SERVER_URL}/usermanagement/api/auth/updateWarehouse?warehouseId=`,
      GetEOLInfoBySerialNumber:`${TEST_SERVER_URL}/lastmilemanagement/api/GetEOLInfoBySerialNumber?serial_number=`,
      GetEOLInfoByProductId:`${TEST_SERVER_URL}/lastmilemanagement/api/GetEOLInfoByProductId?id=`,
      GetEOLInfoByIdentityId:`${TEST_SERVER_URL}/lastmilemanagement/api/GetEOLInfoByIdentityId?id=`,
      GetEOLInfoByPlaceAdministered:`${TEST_SERVER_URL}/lastmilemanagement/api/GetEOLInfoByPlaceAdministered?place=`,
      GetEOLListByDateWindow:`${TEST_SERVER_URL}/lastmilemanagement/api/GetEOLListByDateWindow`,
      getWarehouseById: `${TEST_SERVER_URL}/usermanagement/api/auth/getwarehouseinfo?id=`,
      addWarehouse: `${TEST_SERVER_URL}/usermanagement/api/auth/addWarehouse`,
      addPOsFromExcel:`${TEST_SERVER_URL}/pomanagement/api/po/addPOsFromExcel`,
      getOrganizationsTypewithauth:`${TEST_SERVER_URL}/usermanagement/api/auth/getOrganizationsTypewithauth?id=`,
      getTransactions: `${TEST_SERVER_URL}/eventmanagement/api/event/getAllEventsWithFilter`,
      getTransactionFilterList: `${TEST_SERVER_URL}/eventmanagement/api/event/fetchProductDetailsList`,
      getRegionsUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getRegions`,
      getCountryByRegionUrl: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getCountryDetailsByRegion?region=`,
      getAllStates: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getAllStates`,
      getDistrictsByState: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getDistrictsByState`,
      GetEOLInfo:`${TEST_SERVER_URL}/lastmilemanagement/api/GetEOLInfo`,
      GetProductsByWarehouse:`${TEST_SERVER_URL}/lastmilemanagement/api/getProductsByWarehouse`,
      getCountries: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getCountries`,
      getStatesByCountry: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getStatesByCountry`,
      getCitiesByState: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getCitiesByState`,
      getWarehousesByCity: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/getWarehousesByCity`,
      emailverify:`${TEST_SERVER_URL}/usermanagement/api/auth/emailverify`,
      fetchairwayBillNumber:`${TEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchairwayBillNumber`,
      fetchAllRegions:`${TEST_SERVER_URL}/productmanagement/api/location?region=all`,
      fetchCountriesByRegion:`${TEST_SERVER_URL}/productmanagement/api/location?region=`,
      fetchStateByCountry:`${TEST_SERVER_URL}/productmanagement/api/location?country_id=`,
      fetchCitiesByState:`${TEST_SERVER_URL}/productmanagement/api/location?state_id=`,
      searchProduct:`${TEST_SERVER_URL}/inventorymanagement/api/inventory/searchProduct?skip=0&limit=10`,
      getSuggestions:`${TEST_SERVER_URL}/inventorymanagement/api/inventory/getsearchsuggestions`,
      fetchBatchesOfInventory: `${TEST_SERVER_URL}/inventorymanagement/api/inventory/fetchBatchesOfInventory`,
      getAlerts: `${TEST_SERVER_URL}/alertmanagement/api/alert/getAlertNotifications?type=`,
      getExportFileForInboundShipmentUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/exportInboundShipments`,
      getExportFileForOutboundShipmentUrl: `${TEST_SERVER_URL}/shipmentmanagement/api/shipment/exportOutboundShipment`,
      getExportFileForInboundPurchaseOrdersUrl: `${TEST_SERVER_URL}/pomanagement/api/po/exportInboundPurchaseOrders`,
      getExportFileForOutboundPurchaseOrdersUrl:  `${TEST_SERVER_URL}/pomanagement/api/po/exportOutboundPurchaseOrders`
},
    prod: {
      getOrganizationsUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getOrganizations?orgType=`,
      loginUrl: `${PROD_SERVER_URL}/usermanagement/api/auth/login`,
      sendOtpUrl: `${PROD_SERVER_URL}/usermanagement/api/auth/sendOtp`,
      registerUrl: `${PROD_SERVER_URL}/usermanagement/api/auth/register`,
      checkUserUrl: `${PROD_SERVER_URL}/usermanagement/api/auth/check`,
      verifyOtpUrl: `${PROD_SERVER_URL}/usermanagement/api/auth/verifyOtp`,
      userInfoUrl: `${PROD_SERVER_URL}/usermanagement/api/auth/userInfo`,
      getAllUsersUrl: `${PROD_SERVER_URL}/api/auth/getAllUsers`,
      locationUrl: `${PROD_SERVER_URL}/usermanagement/api/auth/switchLocation`,
      updateProfileUrl: `${PROD_SERVER_URL}/usermanagement/api/auth/updateProfile`,
      upload: `${PROD_SERVER_URL}/usermanagement/api/auth/uploadImage?`,
      fetchProfileImage:`${PROD_SERVER_URL}`,
      uploadProfileImage:`${PROD_SERVER_URL}/usermanagement/api/auth/uploadImage?action=PROFILE`,
      getAnalyticsUrl:`${PROD_SERVER_URL}/analyticsmanagement/api/analytics/getAnalytics`,
      getOverviewAnalyticsUrl:`${PROD_SERVER_URL}/analyticsmanagement/api/analytics/getOverviewAnalytics`,
      getInventoryAnalyticsUrl:`${PROD_SERVER_URL}/analyticsmanagement/api/analytics/getInventoryAnalytics`,
      getShipmentAnalyticsUrl:`${PROD_SERVER_URL}/analyticsmanagement/api/analytics/getShipmentAnalytics`,
      getOrderAnalyticsUrl:`${PROD_SERVER_URL}/analyticsmanagement/api/analytics/getOrderAnalytics`,
      shipmentsUrl: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/fetchShipments`,
      viewShipmentUrl: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/viewShipment?shipmentId=`,
      getShipmentIdsUrl: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/fetchShipmentIds`,
      chainOfCustody: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/chainOfCustody?shipmentId=`,    
      receiveApi: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/receiveShipment`,
      fetchImage: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/fetchImage?id=`, 
      getImage: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment`,    
      uploadImage: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/uploadImage?id=`,                  
      createShippingOrderUrl:`${PROD_SERVER_URL}/shippingordermanagement/api/shipping/createShippingOrder`,
      getShippingOrdersUrl:`${PROD_SERVER_URL}/shippingordermanagement/api/shipping/getShippingOrders`,
      getShippingOrderIdsUrl:`${PROD_SERVER_URL}/shippingordermanagement/api/shipping/getShippingOrderIds`,
      viewShippingOrderUrl:`${PROD_SERVER_URL}/shippingordermanagement/api/shipping/viewShippingOrder?soId=`,
      shipmentsSearch: `${PROD_SERVER_URL}/shipmentmanagement/api/shipping/fetchShipments?key=`,
      getProducts: `${PROD_SERVER_URL}/productmanagement/api/products/getProducts`,
      getProductsByCategoryUrl: `${PROD_SERVER_URL}/productmanagement/api/products/getProductsByCategory?type=`,
      getProductsByInventoryUrl: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/getProductsByInventory?invId=`,
      generateCodes: `${PROD_SERVER_URL}/productmanagement/api/products/generateCodes`,
      getManufacturers: `${PROD_SERVER_URL}/productmanagement/api/products/getManufacturer`,
      createPurchaseOrderUrl: `${PROD_SERVER_URL}/pomanagement/api/po/createPurchaseOrder`,
      createOrderUrl: `${PROD_SERVER_URL}/pomanagement/api/po/createOrder`,
      fetchPurchaseOrderUrl: `${PROD_SERVER_URL}/pomanagement/api/po/fetchPurchaseOrders`,
      fetchPurchaseOrderById: `${PROD_SERVER_URL}/pomanagement/api/po/fetchPurchaseOrders?skip=0&limit=5&poId=`,
      createShipmentUrl: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/createShipment`,
      changePOStatus: `${PROD_SERVER_URL}/pomanagement/api/po/changePOStatus`,
      fetchAllPurchaseOrderUrl: `${PROD_SERVER_URL}/shipmentmanagement/api/shipping/fetchpurchaseOrder?key=`,
      getPOsUrl: `${PROD_SERVER_URL}/pomanagement/api/po/purchaseOrderStatistics`,
      inventoriesUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getInventory`,
      bacthcNearExpiryUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getBatchNearExpiration`,
      batchExpiredUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getBatchExpired`,
      batchWarehouseUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getBatchWarehouse`,
      inventorySearch: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getInventoryDetailsForProduct?key=`,
      getSerialNumbersByBatchNumber: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getInventoryDetailsByBatchNumber?skip=0&limit=100&batchNumber=`,
      getInventoryDetailsUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getInventoryDetails`,
      getInventoryByBatchNumber:`${PROD_SERVER_URL}/inventorymanagement/api/inventory/getBatchDetailsByBatchNumber?skip=0&limit=100&batchNumber=`,
      addInventoryUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/addNewInventory`,
      addProductsToInventory: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/addProductsToInventory`,
      productListUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getProductListCounts`,
      addInventoriesFromExcel: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/addInventoriesFromExcel`,
      getProductDetailsByWarehouseIdUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getProductDetailsByWarehouseId?warehouseId=`,
      getRegionsUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getRegions`,
      getCountryByRegionUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getCountryDetailsByRegion?region=`,
      getWarehouseDetailsByCountryUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getWarehouseDetailsByCountry?name=`,
      getWareHousesByCountryUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getWarehouseDetailsByCountry?country=`,
      trackShipment: `${PROD_SERVER_URL}/shipmentmanagement/api/shipping/trackShipment?shipmentId=`,
      trackShipmentJourney: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/trackJourney?trackingId=`,
      trackJourney: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/trackJourney?trackingId=`,
      poDetailsByShipmentId:`${PROD_SERVER_URL}/shipmentmanagement/api/shipping/fetchPOdetailsByShipmentID?shipmentId=`,
      productDetailsByShipmentId:`${PROD_SERVER_URL}/shipmentmanagement/api/shipping/fetchProductdetailsByShipmentID?shipmentId=`,
      trackTemperature: `${PROD_SERVER_URL}/tracktracemanagement/api/track/fetchTemp`,
      trackProduct: `${PROD_SERVER_URL}/tracktracemanagement/api/track/track?trackingNumber=`,
      getOrganisations:`${PROD_SERVER_URL}/productmanagement/api/organisation/getOrganisations`,
      getOrganizationsByType:`${PROD_SERVER_URL}/usermanagement/api/auth/getOrganizationsByType?id=`,
      getwarehouseByType:`${PROD_SERVER_URL}/usermanagement/api/auth/getwarehouseByType?id=`,
      getWarehouseByOrgId:`${PROD_SERVER_URL}/productmanagement/api/organisation/warehouses?id=`,
      getAllWarehouses:`${PROD_SERVER_URL}/productmanagement/api/organisation/allWarehouses`,
      addNewProduct: `${PROD_SERVER_URL}/productmanagement/api/products/addProduct`,
      addMultipleProducts: `${PROD_SERVER_URL}/productmanagement/api/products/addMultipleProducts`,
      getNotificationsUrl: `${PROD_SERVER_URL}/notificationmanagement/api/notification/getNotifications`,
      deleteNotificationUrl: `${PROD_SERVER_URL}/notificationmanagement/api/notification/deleteNotification`,
      updateTrackingStatusUrl:`${PROD_SERVER_URL}/shipmentmanagement/api/shipment/updateTrackingStatus`,
      getOrderIds:`${PROD_SERVER_URL}/pomanagement/api/po/getOrderIds`,
      getOpenOrderIds:`${PROD_SERVER_URL}/pomanagement/api/po/getOpenOrderIds`,
      addWarehouse: `${PROD_SERVER_URL}/usermanagement/api/auth/addWarehouse`, 
      updateWarehouse: `${PROD_SERVER_URL}/usermanagement/api/auth/updateWarehouse?warehouseId=`,
      GetEOLInfoBySerialNumber:`${PROD_SERVER_URL}/lastmilemanagement/api/GetEOLInfoBySerialNumber?serial_number=`,
      GetEOLInfoByProductId:`${PROD_SERVER_URL}/lastmilemanagement/api/GetEOLInfoByProductId?id=`,
      GetEOLInfoByIdentityId:`${PROD_SERVER_URL}/lastmilemanagement/api/GetEOLInfoByIdentityId?id=`,
      GetEOLInfoByPlaceAdministered:`${PROD_SERVER_URL}/lastmilemanagement/api/GetEOLInfoByPlaceAdministered?place=`,
      GetEOLListByDateWindow:`${PROD_SERVER_URL}/lastmilemanagement/api/GetEOLListByDateWindow`,
      getWarehouseById: `${PROD_SERVER_URL}/usermanagement/api/auth/getwarehouseinfo?id=`,
      addPOsFromExcel:`${PROD_SERVER_URL}/pomanagement/api/po/addPOsFromExcel`,
      getOrganizationsTypewithauth:`${PROD_SERVER_URL}/usermanagement/api/auth/getOrganizationsTypewithauth?id=`,
      getTransactions: `${PROD_SERVER_URL}/eventmanagement/api/event/getAllEventsWithFilter`,
      getTransactionFilterList: `${PROD_SERVER_URL}/eventmanagement/api/event/fetchProductDetailsList`,
      getRegionsUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getRegions`,
      getCountryByRegionUrl: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getCountryDetailsByRegion?region=`,
      getAllStates: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getAllStates`,
      getDistrictsByState: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getDistrictsByState`,
      GetProductsByWarehouse:`${PROD_SERVER_URL}/lastmilemanagement/api/getProductsByWarehouse`,
      GetEOLInfo:`${PROD_SERVER_URL}/lastmilemanagement/api/GetEOLInfo`,
      getCountries: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getCountries`,
      getStatesByCountry: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getStatesByCountry`,
      getCitiesByState: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getCitiesByState`,
      getWarehousesByCity: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/getWarehousesByCity`,
      emailverify:`${PROD_SERVER_URL}/usermanagement/api/auth/emailverify`,
      fetchairwayBillNumber:`${PROD_SERVER_URL}/shipmentmanagement/api/shipment/fetchairwayBillNumber`,
      fetchAllRegions:`${PROD_SERVER_URL}/productmanagement/api/location?region=all`,
      fetchCountriesByRegion:`${PROD_SERVER_URL}/productmanagement/api/location?region=`,
      fetchStateByCountry:`${PROD_SERVER_URL}/productmanagement/api/location?country_id=`,
      fetchCitiesByState:`${PROD_SERVER_URL}/productmanagement/api/location?state_id=`,
      getIotEnabledStatus:`${PROD_SERVER_URL}/productmanagement/api/products/getIotEnabledStatus`,
      trackLastTenIotShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/lastteniotsamplesforshipmentid/:shipmentId`,
      trackLatestShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/latestiotdataforshipmentid/:shipmentId`,
      trackAllIotShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/alliotsamplesforshipmentid/:shipmentId`,
      searchProduct:`${PROD_SERVER_URL}/inventorymanagement/api/inventory/searchProduct?skip=0&limit=10`,
      getSuggestions:`${PROD_SERVER_URL}/inventorymanagement/api/inventory/getsearchsuggestions`,
      fetchBatchesOfInventory: `${PROD_SERVER_URL}/inventorymanagement/api/inventory/fetchBatchesOfInventory`,
      getAlerts: `${PROD_SERVER_URL}/alertmanagement/api/alert/getAlertNotifications?type=`,
      getExportFileForInboundShipmentUrl: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/exportInboundShipments`,
      getExportFileForOutboundShipmentUrl: `${PROD_SERVER_URL}/shipmentmanagement/api/shipment/exportOutboundShipment`,
      getExportFileForInboundPurchaseOrdersUrl: `${PROD_SERVER_URL}/pomanagement/api/po/exportInboundPurchaseOrders`,
      getExportFileForOutboundPurchaseOrdersUrl:  `${PROD_SERVER_URL}/pomanagement/api/po/exportOutboundPurchaseOrders`
    },
    unicef: {
      getOrganizationsUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getOrganizations?orgType=`,
      loginUrl: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/login`,
      sendOtpUrl: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/sendOtp`,
      registerUrl: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/register`,
      checkUserUrl: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/check`,
      verifyOtpUrl: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/verifyOtp`,
      userInfoUrl: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/userInfo`,
      locationUrl: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/switchLocation`,
      getAllUsersUrl: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/getAllUsers`,
      updateProfileUrl: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/updateProfile`,
      upload: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/uploadImage?`,
      fetchProfileImage:`${UNICEFTEST_SERVER_URL}`,
      uploadProfileImage:`${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/uploadImage?action=PROFILE`,
      getAnalyticsUrl:`${UNICEFTEST_SERVER_URL}/analyticsmanagement/api/analytics/getAnalytics`,
      getOverviewAnalyticsUrl:`${UNICEFTEST_SERVER_URL}/analyticsmanagement/api/analytics/getOverviewAnalytics`,
      getInventoryAnalyticsUrl:`${UNICEFTEST_SERVER_URL}/analyticsmanagement/api/analytics/getInventoryAnalytics`,
      getShipmentAnalyticsUrl:`${UNICEFTEST_SERVER_URL}/analyticsmanagement/api/analytics/getShipmentAnalytics`,
      getOrderAnalyticsUrl:`${UNICEFTEST_SERVER_URL}/analyticsmanagement/api/analytics/getOrderAnalytics`,
      shipmentsUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchShipments`,
      viewShipmentUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/viewShipment?shipmentId=`,
      chainOfCustody: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/chainOfCustody?shipmentId=`, 
      receiveApi: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/receiveShipment`,
      getShipmentIdsUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchShipmentIds`,
      fetchImage: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchImage?id=`, 
      getImage: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment`,  
      uploadImage: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/uploadImage?id=`,                  
      getManufacturers: `${UNICEFTEST_SERVER_URL}/productmanagement/api/products/getManufacturer`,
      createShippingOrderUrl:`${UNICEFTEST_SERVER_URL}/shippingordermanagement/api/shipping/createShippingOrder`,
      getShippingOrdersUrl:`${UNICEFTEST_SERVER_URL}/shippingordermanagement/api/shipping/getShippingOrders`,
      getShippingOrderIdsUrl:`${UNICEFTEST_SERVER_URL}/shippingordermanagement/api/shipping/getShippingOrderIds`,
      viewShippingOrderUrl:`${UNICEFTEST_SERVER_URL}/shippingordermanagement/api/shipping/viewShippingOrder?soId=`,
      createShipmentUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/createShipment`,
      shipmentsSearch: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipping/fetchShipments?key=`,
      createPurchaseOrderUrl: `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/createPurchaseOrder`,
      createOrderUrl: `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/createOrder`,
      fetchPurchaseOrderUrl: `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/fetchPurchaseOrders`,
      fetchPurchaseOrderById: `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/fetchPurchaseOrders?skip=0&limit=5&poId=`,
      changePOStatus: `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/changePOStatus`,
      fetchAllPurchaseOrderUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipping/fetchpurchaseOrder?key=`,
      getPOsUrl: `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/purchaseOrderStatistics`,
      inventoriesUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getInventory`,
      bacthcNearExpiryUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getBatchNearExpiration`,
      batchExpiredUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getBatchExpired`,
      batchWarehouseUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getBatchWarehouse`,
      inventorySearch: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getInventoryDetailsForProduct?key=`,
      getSerialNumbersByBatchNumber: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getInventoryDetailsByBatchNumber?skip=0&limit=100&batchNumber=`,
      getInventoryDetailsUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getInventoryDetails`,
      getInventoryByBatchNumber:`${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getBatchDetailsByBatchNumber?skip=0&limit=100&batchNumber=`,
      addProductsToInventory: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/addProductsToInventory`,
      addInventoriesFromExcel: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/addInventoriesFromExcel`,
      addInventoryUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/addNewInventory`,
      productListUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getProductListCounts`,
      getProductDetailsByWarehouseIdUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getProductDetailsByWarehouseId?warehouseId=`,
      getRegionsUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getRegions`,
      getCountryByRegionUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getCountryDetailsByRegion?region=`,
      getWareHousesByCountryUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getWarehouseDetailsByCountry?country=`,
      getWarehouseDetailsByCountryUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getWarehouseDetailsByCountry?name=`,
      getWareHousesByRegionUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getWarehouseDetailsByRegion?region=`,
      trackShipment: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipping/trackShipment?shipmentId=`,
      trackShipmentJourney: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/trackJourney?trackingId=`,
      trackJourney: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/trackJourney?trackingId=`,
      poDetailsByShipmentId:`${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipping/fetchPOdetailsByShipmentID?shipmentId=`,
      productDetailsByShipmentId:`${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipping/fetchProductdetailsByShipmentID?shipmentId=`,
      trackTemperature: `${UNICEFTEST_SERVER_URL}/tracktracemanagement/api/track/fetchTemp`,
      trackProduct: `${UNICEFTEST_SERVER_URL}/tracktracemanagement/api/track/track?trackingNumber=`,
      getOrganisations:`${UNICEFTEST_SERVER_URL}/productmanagement/api/organisation/getOrganisations`,
      getOrganizationsByType:`${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/getOrganizationsByType?id=`,
      getwarehouseByType:`${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/getwarehouseByType?id=`,
      getWarehouseByOrgId:`${UNICEFTEST_SERVER_URL}/productmanagement/api/organisation/warehouses?id=`,
      getAllWarehouses:`${UNICEFTEST_SERVER_URL}/productmanagement/api/organisation/allWarehouses`,
      addNewProduct: `${UNICEFTEST_SERVER_URL}/productmanagement/api/products/addProduct`,
      getProducts: `${UNICEFTEST_SERVER_URL}/productmanagement/api/products/getProducts`,
      getProductsByCategoryUrl: `${UNICEFTEST_SERVER_URL}/productmanagement/api/products/getProductsByCategory?type=`,
      getProductsByInventoryUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/getProductsByInventory?invId=`,
      generateCodes: `${UNICEFTEST_SERVER_URL}/productmanagement/api/products/generateCodes`,
      addMultipleProducts: `${UNICEFTEST_SERVER_URL}/productmanagement/api/products/addMultipleProducts`,
      getNotificationsUrl: `${UNICEFTEST_SERVER_URL}/notificationmanagement/api/notification/getNotifications`,
      deleteNotificationUrl: `${UNICEFTEST_SERVER_URL}/notificationmanagement/api/notification/deleteNotification`,
      updateTrackingStatusUrl:`${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/updateTrackingStatus`,
      getOrderIds:`${UNICEFTEST_SERVER_URL}/pomanagement/api/po/getOrderIds`,
      getOpenOrderIds:`${UNICEFTEST_SERVER_URL}/pomanagement/api/po/getOpenOrderIds`,
      addWarehouse: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/addWarehouse`, 
      updateWarehouse: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/updateWarehouse?warehouseId=`,
      GetEOLInfoBySerialNumber:`${UNICEFTEST_SERVER_URL}/lastmilemanagement/api/GetEOLInfoBySerialNumber?serial_number=`,
      GetEOLInfoByProductId:`${UNICEFTEST_SERVER_URL}/lastmilemanagement/api/GetEOLInfoByProductId?id=`,
      GetEOLInfoByIdentityId:`${UNICEFTEST_SERVER_URL}/lastmilemanagement/api/GetEOLInfoByIdentityId?id=`,
      GetEOLInfoByPlaceAdministered:`${UNICEFTEST_SERVER_URL}/lastmilemanagement/api/GetEOLInfoByPlaceAdministered?place=`,
      GetEOLListByDateWindow:`${UNICEFTEST_SERVER_URL}/lastmilemanagement/api/GetEOLListByDateWindow`,
      getWarehouseById: `${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/getwarehouseinfo?id=`,
      addPOsFromExcel:`${UNICEFTEST_SERVER_URL}/pomanagement/api/po/addPOsFromExcel`,
      getOrganizationsTypewithauth:`${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/getOrganizationsTypewithauth?id=`,
      getTransactions: `${UNICEFTEST_SERVER_URL}/eventmanagement/api/event/getAllEventsWithFilter`,
      getTransactionFilterList: `${UNICEFTEST_SERVER_URL}/eventmanagement/api/event/fetchProductDetailsList`,
      fetchOutboundPurchaseOrderUrl: `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/fetchOutboundPurchaseOrders`,
      fetchInboundPurchaseOrderUrl: `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/fetchInboundPurchaseOrders`,
      fetchProductIdsCustomerLocationsOrganisationsUrl: `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/fetchProductIdsCustomerLocationsOrganisations`,
      fetchInboundShipmentsUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchInboundShipments`,
      fetchOutboundShipmentsUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchOutboundShipments`,
      fetchSupplierAndReceiverListUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchSupplierAndReceiverList`,
      getRegionsUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getRegions`,
      getCountryByRegionUrl: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getCountryDetailsByRegion?region=`,
      getAllStates: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getAllStates`,
      getDistrictsByState: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getDistrictsByState`,
      GetProductsByWarehouse:`${UNICEFTEST_SERVER_URL}/lastmilemanagement/api/getProductsByWarehouse`,
      GetEOLInfo:`${UNICEFTEST_SERVER_URL}/lastmilemanagement/api/GetEOLInfo`,
      getCountries: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getCountries`,
      getStatesByCountry: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getStatesByCountry`,
      getCitiesByState: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getCitiesByState`,
      getWarehousesByCity: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getWarehousesByCity`,
      emailverify:`${UNICEFTEST_SERVER_URL}/usermanagement/api/auth/emailverify`,
      fetchairwayBillNumber:`${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/fetchairwayBillNumber`,
      fetchAllRegions:`${UNICEFTEST_SERVER_URL}/productmanagement/api/location?region=all`,
      fetchCountriesByRegion:`${UNICEFTEST_SERVER_URL}/productmanagement/api/location?region=`,
      fetchStateByCountry:`${UNICEFTEST_SERVER_URL}/productmanagement/api/location?country_id=`,
      fetchCitiesByState:`${UNICEFTEST_SERVER_URL}/productmanagement/api/location?state_id=`,
      getIotEnabledStatus:`${UNICEFTEST_SERVER_URL}/productmanagement/api/products/getIotEnabledStatus`,
      trackLastTenIotShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/lastteniotsamplesforshipmentid/:shipmentId`,
      trackLatestShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/latestiotdataforshipmentid/:shipmentId`,
      trackAllIotShipmentData: `${TEST_SERVER_URL_FOR_ROAMBEE}/integrationmanagement/api/v1/roambee/alliotsamplesforshipmentid/:shipmentId`,
      searchProduct:`${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/searchProduct?skip=0&limit=10`,
      getSuggestions:`${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/getsearchsuggestions`,
      fetchBatchesOfInventory: `${UNICEFTEST_SERVER_URL}/inventorymanagement/api/inventory/fetchBatchesOfInventory`,
      getAlerts: `${UNICEFTEST_SERVER_URL}/alertmanagement/api/alert/getAlertNotifications?type=`,
      getExportFileForInboundShipmentUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/exportInboundShipments`,
      getExportFileForOutboundShipmentUrl: `${UNICEFTEST_SERVER_URL}/shipmentmanagement/api/shipment/exportOutboundShipment`,
      getExportFileForInboundPurchaseOrdersUrl: `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/exportInboundPurchaseOrders`,
      getExportFileForOutboundPurchaseOrdersUrl:  `${UNICEFTEST_SERVER_URL}/pomanagement/api/po/exportOutboundPurchaseOrders`
    },
  };

  const environment = process.env.ENVIRONMENT || `test`; // change for respective environments
  const conf = confs[environment];
  return conf;
}
