export const GET_SHIPMENTS_SUCCESS = 'GET_SHIPMENTS_SUCCESS';
export const GET_SHIPMENTS_FAILURE = 'GET_SHIPMENTS_FAILURE';
export const SET_REVIEW_SHIPMENT = 'SET_REVIEW_SHIPMENT';
export const SET_TRACING_SHIPMENT = 'SET_TRACING_SHIPMENT';
export const SET_TRACK_SHIPMENT = 'SET_TRACK_SHIPMENT';
export const GET_SHIPMENTSCOUNT_SUCCESS = 'GET_SHIPMENTSCOUNT_SUCCESS';
export const GET_SHIPMENTSCOUNT_FAILURE = 'GET_SHIPMENTSCOUNT_FAILURE';
export const SET_EDIT_SHIPMENT = 'SET_EDIT_SHIPMENT';
export const SET_VISIBLE_SHIPMENT = 'SET_VISIBLE_SHIPMENT';

